### ISSUE TITLE
node-sass middleware has been moved to node-sass-middleware

### ISSUE THREAD

**Issue by adamkdean** [kasperlewau/koa-sass#2]
FYI, node-sass middleware has been moved to node-sass-middleware.

https://github.com/sass/node-sass-middleware

**Comment by kasperlewau** [comment]
separate project altogether, but cheers for the heads up! 

Haven't used/updated this package (or sass for that matter), since before node-sass-middleware was created : )

**Comment by kasperlewau** [comment]
wow. I'm so daft, I read that as koa-sass-middleware.

i'll get it fixed in a wee bit, not tonight however : )
