### ISSUE TITLE
TypeError: undefined is not a function

### ISSUE THREAD

**Issue by dingledow** [kasperlewau/koa-sass#3]
Having some issues using koa-sass following your usage example on [https://www.npmjs.com/package/koa-sass](https://www.npmjs.com/package/koa-sass)

`node-sass` dependency has been installed.

```
/path/to/node_modules/koa-sass/index.js:2
var mw = require('node-sass').middleware(options);

/path/to/node_modules/koa-sass/index.js:2
var mw = require('node-sass').middleware(options);
                            ^
TypeError: undefined is not a function
    at module.exports (/path/to/node_modules/koa-sass/index.js:2:33)
    at Object.<anonymous> (/path/to/index.js:26:9)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

**Comment by kasperlewau** [comment]
Yeah, `node-sass` has moved on to `node-sass-middleware` - I believe that may be the cause here. 

~~I should probably update that example.~~

Which version of koa-sass are you currently running by the way? Updates have been made to the package so as to use `node-sass-middleware`.

**Comment by kasperlewau** [comment]
ping @dingledow 

Could you give it a whirl with the latest version (`1.0.1`)? 

Thanks to #4, we're now running `node-sass-middleware` _without_ the `.middleware` method. 

_Should just work™_.

**Comment by HowlingEverett** [comment]
Heya,

Looks like the npm repository version is still at 1.0.0, and is still using the old require('node-sass').middleware function.

Based on the repo here, my guess is you just need to `npm publish` :)

**Comment by kasperlewau** [comment]
**doh!**

Thanks @HowlingEverett. 

[koa-sass@1.0.1](https://www.npmjs.com/package/koa-sass)
